### ISSUE TITLE
Failing with current lexibank installation

### ISSUE THREAD

**Issue by tresoldi** [lexibank/hruschkaturkic#2]
`hruschkaturkic` is currently failing with the current `pylexibank` installation; once installed from `pip`, `lexibank curate` will fail with the following output:

```
(env) tresoldi@shh.mpg.de@dlt5802808l:~/src/lexibank$ lexibank curate
Traceback (most recent call last):
  File "/home/tresoldi/src/lexibank/env/bin/lexibank", line 11, in <module>
    sys.exit(main())
  File "/home/tresoldi/src/lexibank/env/lib/python3.5/site-packages/pylexibank/__main__.py", line 116, in main
    cfg, datasets = configure()
  File "/home/tresoldi/src/lexibank/env/lib/python3.5/site-packages/pylexibank/__main__.py", line 106, in configure
    key=lambda d: d.id)
  File "/home/tresoldi/src/lexibank/env/lib/python3.5/site-packages/pylexibank/dataset.py", line 662, in iter_datasets
    yield ep.load()(glottolog=glottolog, concepticon=concepticon)
  File "/home/tresoldi/src/lexibank/env/lib/python3.5/site-packages/pylexibank/dataset.py", line 201, in __init__
    raise ValueError
ValueError
```

Taking a quick look, this seems to stem from changes in the `BaseDataset` object.

**Comment by tresoldi** [comment]
Ok, it was just a missing id, fixed here: https://github.com/lexibank/hruschkaturkic/commit/e12d9c6ac1d7555bc121940119b643c6d32df93c

The dataset is not compiling due to some division by zero, but at least it is not interfering with the overall lexibank setup.

**Comment by LinguList** [comment]
The problem with the dataset is that it's an etymological dictionary, converted later into some set of alignments. So we have no real means to use it, unfortunately, as we lack the meanings of the individual items. But it could be used for testing alignment systems or benchmarks.

**Comment by tresoldi** [comment]
Yes, it was just because I was installing all the datasets automatically and the entire system was failing. The division by zero is due to no lexemes being added, but we should not concern with that now.
